### ISSUE TITLE
Publish

### ISSUE THREAD

**Issue by knownasilya** [transitland/ember-leaflet-draw#1]
Any plans on adding a readme and publishing to npm? I'm sure you could also submit a PR to ember-leaflet to add this to their site.

**Comment by doublestranded** [comment]
Hi @knownasilya thank you for your interest! There were no concrete plans to publish this to npm - right now it exists mainly to support internal functionality for https://github.com/transitland/dispatcher.

In the meantime, it looks like there is a more complete package that was released recently: https://www.npmjs.com/package/ember-leaflet-draw
https://github.com/StevenHeinrich/ember-leaflet-draw
